# Builds and publishes a container image to docker.elastic.co/observability-ci/apm-perf:latest
# This workflow is triggered on push to main branch when cmd, loadgen, soaktest, Containerfile or this file are changed
name: publish-docker-images

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish-docker-image.yml"
      - "cmd/**"
      - "loadgen/**"
      - "soaktest/**"
      - "Containerfile"

permissions:
  contents: read

jobs:
  publish-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Elastic Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ secrets.ELASTIC_DOCKER_REGISTRY }}
          username: ${{ secrets.ELASTIC_DOCKER_USERNAME }}
          password: ${{ secrets.ELASTIC_DOCKER_PASSWORD }}
      - name: Push container image
        run: make publish
